const fs = require('fs');

const file = 'dist_backup/assets/index-sn777-v5.js';
let content = fs.readFileSync(file, 'utf8');

// 1. Change text for active channels
content = content.replace('১টি চ্যানেল সক্রিয়', '২টি চ্যানেল সক্রিয়');

// 2. Initial state
content = content.replace('R.useState("normal")', 'R.useState("propay")');

// 3. Replace Button 1
const btn1Old = 'o.jsxs("button",{type:"button",style:{display:"none"},style:{display:"none"},onClick:()=>setDepCh("normal"),className:`relative rounded-2xl p-3.5 flex items-center justify-between text-left transition-all duration-300 ${depCh==="propay"?"bg-gradient-to-r from-blue-50/90 via-blue-50/40 to-white border-2 border-[#00559b] shadow-[0_4px_14px_rgba(0,85,155,0.12)] -translate-y-0.5":"bg-white border-2 border-slate-100 hover:border-slate-300 hover:shadow-sm"}`,children:[o.jsxs("div",{className:"flex flex-col gap-0.5",children:[o.jsxs("div",{className:"flex items-center gap-2",children:[o.jsx("span",{className:`text-xs font-black uppercase tracking-tight flex items-center gap-1.5 ${depCh==="propay"?"text-[#00559b]":"text-slate-700"}`,children:[o.jsx("span",{className:"w-2 h-2 rounded-full bg-emerald-500 animate-pulse"}),"PROPAY"]}),o.jsx("span",{className:"text-[9px] font-black bg-emerald-100 text-emerald-700 px-2 py-0.5 rounded-full",children:"ইনস্ট্যান্ট"})]}),o.jsx("span",{className:"text-[11px] font-bold text-slate-500",children:"(অটো গেটওয়ে)"})]}),depCh==="propay"?o.jsx("div",{className:"bg-[#00559b] text-white w-5 h-5 rounded-full flex items-center justify-center shadow-sm shrink-0",children:o.jsx(Oa,{size:11,strokeWidth:4})}):o.jsx("div",{className:"w-5 h-5 rounded-full border-2 border-slate-300 shrink-0"})]})';
const btn1New = 'o.jsxs("button",{type:"button",onClick:()=>setDepCh("propay"),className:`relative rounded-2xl p-3.5 flex items-center justify-between text-left transition-all duration-300 ${depCh==="propay"?"bg-gradient-to-r from-blue-50/90 via-blue-50/40 to-white border-2 border-[#00559b] shadow-[0_4px_14px_rgba(0,85,155,0.12)] -translate-y-0.5":"bg-white border-2 border-slate-100 hover:border-slate-300 hover:shadow-sm"}`,children:[o.jsxs("div",{className:"flex flex-col gap-0.5",children:[o.jsxs("div",{className:"flex items-center gap-2",children:[o.jsx("span",{className:`text-xs font-black uppercase tracking-tight flex items-center gap-1.5 ${depCh==="propay"?"text-[#00559b]":"text-slate-700"}`,children:[o.jsx("span",{className:"w-2 h-2 rounded-full bg-emerald-500 animate-pulse"}),"POROPAY"]}),o.jsx("span",{className:"text-[9px] font-black bg-emerald-100 text-emerald-700 px-2 py-0.5 rounded-full",children:"ইনস্ট্যান্ট"})]}),o.jsx("span",{className:"text-[11px] font-bold text-slate-500",children:"(অটো গেটওয়ে)"})]}),depCh==="propay"?o.jsx("div",{className:"bg-[#00559b] text-white w-5 h-5 rounded-full flex items-center justify-center shadow-sm shrink-0",children:o.jsx(Oa,{size:11,strokeWidth:4})}):o.jsx("div",{className:"w-5 h-5 rounded-full border-2 border-slate-300 shrink-0"})]})';

// 4. Replace Button 2
const btn2Old = 'o.jsxs("button",{type:"button",style:{display:"none"},onClick:()=>setDepCh("normal"),className:`relative rounded-2xl p-3.5 flex items-center justify-between text-left transition-all duration-300 ${depCh==="normal"?"bg-gradient-to-r from-blue-50/90 via-blue-50/40 to-white border-2 border-[#00559b] shadow-[0_4px_14px_rgba(0,85,155,0.12)] -translate-y-0.5":"bg-white border-2 border-slate-100 hover:border-slate-300 hover:shadow-sm"}`,children:[o.jsxs("div",{className:"flex flex-col gap-0.5",children:[o.jsxs("div",{className:"flex items-center gap-2",children:[o.jsx("span",{className:`text-xs font-black uppercase tracking-tight flex items-center gap-1.5 ${depCh==="normal"?"text-[#00559b]":"text-slate-700"}`,children:[o.jsx("span",{className:"w-2 h-2 rounded-full bg-slate-400"}),"Auto payment ProPay"]}),o.jsx("span",{className:"text-[9px] font-black bg-blue-100 text-blue-700 px-2 py-0.5 rounded-full",children:"Auto payment ProPay"})]}),o.jsx("span",{className:"text-[11px] font-bold text-slate-500",children:"Auto payment ProPay"})]}),depCh==="normal"?o.jsx("div",{className:"bg-[#00559b] text-white w-5 h-5 rounded-full flex items-center justify-center shadow-sm shrink-0",children:o.jsx(Oa,{size:11,strokeWidth:4})}):o.jsx("div",{className:"w-5 h-5 rounded-full border-2 border-slate-300 shrink-0"})]})';
const btn2New = 'o.jsxs("button",{type:"button",onClick:()=>setDepCh("gopay"),className:`relative rounded-2xl p-3.5 flex items-center justify-between text-left transition-all duration-300 ${depCh==="gopay"?"bg-gradient-to-r from-blue-50/90 via-blue-50/40 to-white border-2 border-[#00559b] shadow-[0_4px_14px_rgba(0,85,155,0.12)] -translate-y-0.5":"bg-white border-2 border-slate-100 hover:border-slate-300 hover:shadow-sm"}`,children:[o.jsxs("div",{className:"flex flex-col gap-0.5",children:[o.jsxs("div",{className:"flex items-center gap-2",children:[o.jsx("span",{className:`text-xs font-black uppercase tracking-tight flex items-center gap-1.5 ${depCh==="gopay"?"text-[#00559b]":"text-slate-700"}`,children:[o.jsx("span",{className:"w-2 h-2 rounded-full bg-blue-500 animate-pulse"}),"GOPay"]}),o.jsx("span",{className:"text-[9px] font-black bg-blue-100 text-blue-700 px-2 py-0.5 rounded-full",children:"ইনস্ট্যান্ট"})]}),o.jsx("span",{className:"text-[11px] font-bold text-slate-500",children:"(অটো গেটওয়ে)"})]}),depCh==="gopay"?o.jsx("div",{className:"bg-[#00559b] text-white w-5 h-5 rounded-full flex items-center justify-center shadow-sm shrink-0",children:o.jsx(Oa,{size:11,strokeWidth:4})}):o.jsx("div",{className:"w-5 h-5 rounded-full border-2 border-slate-300 shrink-0"})]})';

content = content.replace(btn1Old, btn1New);
content = content.replace(btn2Old, btn2New);

// 5. Replace API call routing logic
content = content.replace('jt="/propay_pay.php"', 'jt=(depCh==="gopay"?"/gopay_pay.php":"/propay_pay.php")');
content = content.replace('Le=`/propay_pay.php?uid=${gt.currentUser.uid}&amount=${E}&method=${Be}&order_no=${Te}`', 'Le=`/${depCh==="gopay"?"gopay_pay.php":"propay_pay.php"}?uid=${gt.currentUser.uid}&amount=${E}&method=${Be}&order_no=${Te}`');
content = content.replace('const _fallbackUrl=(Be==="bkash"?"/propay_pay_bkash.php":"/propay_pay.php")+"?uid="', 'const _fallbackUrl=(depCh==="gopay"?"/gopay_pay.php":"/propay_pay.php")+"?uid="');


// Just to be sure we also patch index-CUhzlpga-v3.js which is for some views.
fs.writeFileSync(file, content, 'utf8');
console.log("Successfully patched " + file);
